import {
  to = segment_reverse_etl_model.id-hfviThnmb8qqmjeRheim7j
  id = "hfviThnmb8qqmjeRheim7j"
}

resource "segment_reverse_etl_model" "id-hfviThnmb8qqmjeRheim7j" {
  description             = "Programatically generated rETL model that is associated with an Engage rETL audience"
  enabled                 = true
  name                    = "Use Case 2"
  query                   = "WITH ID_GRAPH AS (\n    SELECT updates.segment_id, updates.canonical_segment_id\n    FROM \"SOLUTIONS_SANDBOX\".\"MARKETING_EAST\".ID_GRAPH_UPDATES AS updates\n    LEFT JOIN \"SOLUTIONS_SANDBOX\".\"MARKETING_EAST\".ID_GRAPH_UPDATES AS updates2 ON updates2.segment_id = updates.canonical_segment_id\n        AND CAST(updates.uuid_ts AS DATETIME) < DATEADD(HOUR, 2, updates2.UUID_TS)\n        AND updates2.canonical_segment_id <> updates2.segment_id\n        AND updates2.canonical_segment_id <> updates.canonical_segment_id\n), PROFILE_TRAITS AS (\n    WITH last_profile_traits_updates AS (\n        SELECT *, ROW_NUMBER() OVER(PARTITION BY segment_id ORDER BY CASE WHEN seq IS NULL THEN '0' ELSE seq END DESC) AS last_record\n        FROM \"SOLUTIONS_SANDBOX\".\"MARKETING_EAST\".PROFILE_TRAITS_UPDATES AS updates\n    )\n    SELECT DISTINCT COALESCE(id_graph.canonical_segment_id,updates.segment_id) AS canonical_segment_id,\n        LAST_VALUE(updates.\"recent_sign_ins\" IGNORE NULLS)\n            OVER(PARTITION BY COALESCE(id_graph.canonical_segment_id,updates.segment_id) ORDER BY updates.seq\n                ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS \"recent_sign_ins\"\n    FROM last_profile_traits_updates AS updates\n    FULL OUTER JOIN ID_GRAPH AS id_graph ON id_graph.segment_id = updates.segment_id\n    WHERE updates.last_record = 1\n), EXTERNAL_ID_MAPPING AS (\n    SELECT COALESCE(id_graph.canonical_segment_id,ids.segment_id) AS canonical_segment_id, ids.external_id_type, ids.external_id_value\n    FROM \"SOLUTIONS_SANDBOX\".\"MARKETING_EAST\".EXTERNAL_ID_MAPPING_UPDATES AS ids\n    LEFT JOIN ID_GRAPH AS id_graph ON id_graph.segment_id = ids.segment_id\n), filtered_query AS (\n  SELECT A.\"CANONICAL_SEGMENT_ID\" AS \"A_CANONICAL_SEGMENT_ID\", B.\"ID\" AS \"B_ID\"\n  FROM \"SOLUTIONS_SANDBOX\".\"MARKETING_EAST\".\"ACCOUNTS\" B\n  INNER JOIN EXTERNAL_ID_MAPPING A ON A.\"EXTERNAL_ID_VALUE\" = B.\"EMAIL_ID\" AND A.\"EXTERNAL_ID_TYPE\" = 'email'\n  INNER JOIN PROFILE_TRAITS PT ON PT.\"CANONICAL_SEGMENT_ID\" = A.\"CANONICAL_SEGMENT_ID\"\n  WHERE ((PT.\"recent_sign_ins\" >= 1) AND (B.\"NUM_EMPLOYEES\" > 1000))\n)\nSELECT DISTINCT CONCAT_WS(':', REPLACE(\"A_CANONICAL_SEGMENT_ID\", ':', '::'), REPLACE(\"B_ID\", ':', '::')) as matchId\nFROM filtered_query\nUNION ALL\nSELECT DISTINCT CONCAT_WS(':', REPLACE(\"A_CANONICAL_SEGMENT_ID\", ':', '::')) as matchId\nFROM filtered_query"
  query_identifier_column = "matchId"
  source_id               = "5nZ2D9s879h4Xc6YQhwh5v"
}